In [1]:
import pymysql
import pandas as pd

host = '127.0.0.1'
port = "3306"
user = 'root'
password = ''
database = 'classicmodels'

conn = pymysql.connect(
    host=host,
    port=int(port),
    user=user,
    passwd=password,
    db=database,
    charset='utf8mb4')

def run(sql):
    df = pd.read_sql_query(sql,conn)
    return df

Inner Join

In [4]:
run("""
SELECT 
    productCode, 
    productName, 
    t1.productline,
    textDescription
FROM
    products t1
        INNER JOIN
    productlines t2 ON t1.productline = t2.productline
""")

,productCode,productName,productline,textDescription
0,S10_1949,1952 Alpine Renault 1300,Classic Cars,Attention car enthusiasts: Make your wildest c...
1,S10_4757,1972 Alfa Romeo GTA,Classic Cars,Attention car enthusiasts: Make your wildest c...
2,S10_4962,1962 LanciaA Delta 16V,Classic Cars,Attention car enthusiasts: Make your wildest c...
3,S12_1099,1968 Ford Mustang,Classic Cars,Attention car enthusiasts: Make your wildest c...
4,S12_1108,2001 Ferrari Enzo,Classic Cars,Attention car enthusiasts: Make your wildest c...
5,S12_3148,1969 Corvair Monza,Classic Cars,Attention car enthusiasts: Make your wildest c...
6,S12_3380,1968 Dodge Charger,Classic Cars,Attention car enthusiasts: Make your wildest c...
7,S12_3891,1969 Ford Falcon,Classic Cars,Attention car enthusiasts: Make your wildest c...
8,S12_3990,1970 Plymouth Hemi Cuda,Classic Cars,Attention car enthusiasts: Make your wildest c...
9,S12_4675,1969 Dodge Charger,Classic Cars,Attention car enthusiasts: Make your wildest c...
10,S18_1129,1993 Mazda RX-7,Classic Cars,Attention car enthusiasts: Make your wildest c...
11,S18_1589,1965 Aston Martin DB5,Classic Cars,Attention car enthusiasts: Make your wildest c...
12,S18_1889,1948 Porsche 356-A Roadster,Classic Cars,Attention car enthusiasts: Make your wildest c...
13,S18_1984,1995 Honda Civic,Classic Cars,Attention car enthusiasts: Make your wildest c...
14,S18_2238,1998 Chrysler Plymouth Prowler,Classic Cars,Attention car enthusiasts: Make your wildest c...
15,S18_2870,1999 Indy 500 Monte Carlo SS,Classic Cars,Attention car enthusiasts: Make your wildest c...
16,S18_3232,1992 Ferrari 360 Spider red,Classic Cars,Attention car enthusiasts: Make your wildest c...
17,S18_3233,1985 Toyota Supra,Classic Cars,Attention car enthusiasts: Make your wildest c...
18,S18_3278,1969 Dodge Super Bee,Classic Cars,Attention car enthusiasts: Make your wildest c...
19,S18_3482,1976 Ford Gran Torino,Classic Cars,Attention car enthusiasts: Make your wildest c...
20,S18_3685,1948 Porsche Type 356 Roadster,Classic Cars,Attention car enthusiasts: Make your wildest c...
21,S18_4027,1970 Triumph Spitfire,Classic Cars,Attention car enthusiasts: Make your wildest c...
22,S18_4721,1957 Corvette Convertible,Classic Cars,Attention car enthusiasts: Make your wildest c...
23,S18_4933,1957 Ford Thunderbird,Classic Cars,Attention car enthusiasts: Make your wildest c...
24,S24_1046,1970 Chevy Chevelle SS 454,Classic Cars,Attention car enthusiasts: Make your wildest c...
25,S24_1444,1970 Dodge Coronet,Classic Cars,Attention car enthusiasts: Make your wildest c...
26,S24_1628,1966 Shelby Cobra 427 S/C,Classic Cars,Attention car enthusiasts: Make your wildest c...
27,S24_2766,1949 Jaguar XK 120,Classic Cars,Attention car enthusiasts: Make your wildest c...
28,S24_2840,1958 Chevy Corvette Limited Edition,Classic Cars,Attention car enthusiasts: Make your wildest c...
29,S24_2887,1952 Citroen-15CV,Classic Cars,Attention car enthusiasts: Make your wildest c...
...,...,...,...,...
80,S18_4600,1940s Ford truck,Trucks and Buses,The Truck and Bus models are realistic replica...
81,S24_2300,1962 Volkswagen Microbus,Trucks and Buses,The Truck and Bus models are realistic replica...
82,S32_1268,1980’s GM Manhattan Express,Trucks and Buses,The Truck and Bus models are realistic replica...
83,S32_2509,1954 Greyhound Scenicruiser,Trucks and Buses,The Truck and Bus models are realistic replica...
84,S32_3522,1996 Peterbilt 379 Stake Bed with Outrigger,Trucks and Buses,The Truck and Bus models are realistic replica...
85,S50_1392,Diamond T620 Semi-Skirted Tanker,Trucks and Buses,The Truck and Bus models are realistic replica...
86,S18_1342,1937 Lincoln Berline,Vintage Cars,Our Vintage Car models realistically portray a...
87,S18_1367,1936 Mercedes-Benz 500K Special Roadster,Vintage Cars,Our Vintage Car models realistically portray a...
88,S18_1749,1917 Grand Touring Sedan,Vintage Cars,Our Vintage Car models realistically portray a...
89,S18_2248,1911 Ford Town Car,Vintage Cars,Our Vintage Car models realistically portray a...
90,S18_2325,1932 Model A Ford J-Coupe,Vintage Cars,Our Vintage Car models realistically portray a...
91,S18_2795,1928 Mercedes-Benz SSK,Vintage Cars,Our Vintage Car models realistically portray a...
92,S18_2949,1913 Ford Model T Speedster,Vintage Cars,Our Vintage Car models realistically portray a...
93,S18_2957,1934 Ford V8 Coupe,Vintage Cars,Our Vintage Car models realistically portray a...
94,S18_3136,18th Century Vintage Horse Carriage,Vintage Cars,Our Vintage Car models realistically portray a...
95,S18_3140,1903 Ford Model A,Vintage Cars,Our Vintage Car models realistically portray a...
96,S18_3320,1917 Maxwell Touring Car,Vintage Cars,Our Vintage Car models realistically portray a...
97,S18_3856,1941 Chevrolet Special Deluxe Cabriolet,Vintage Cars,Our Vintage Car models realistically portray a...
98,S18_4409,1932 Alfa Romeo 8C2300 Spider Sport,Vintage Cars,Our Vintage Car models realistically portray a...
99,S18_4522,1904 Buick Runabout,Vintage Cars,Our Vintage Car models realistically portray a...
100,S18_4668,1939 Cadillac Limousine,Vintage Cars,Our Vintage Car models realistically portray a...
101,S24_1937,1939 Chevrolet Deluxe Coupe,Vintage Cars,Our Vintage Car models realistically portray a...
102,S24_2022,1938 Cadillac V-16 Presidential Limousine,Vintage Cars,Our Vintage Car models realistically portray a...
103,S24_3151,1912 Ford Model T Delivery Wagon,Vintage Cars,Our Vintage Car models realistically portray a...
104,S24_3420,1937 Horch 930V Limousine,Vintage Cars,Our Vintage Car models realistically portray a...
105,S24_3816,1940 Ford Delivery Sedan,Vintage Cars,Our Vintage Car models realistically portray a...
106,S24_3969,1936 Mercedes Benz 500k Roadster,Vintage Cars,Our Vintage Car models realistically portray a...
107,S24_4258,1936 Chrysler Airflow,Vintage Cars,Our Vintage Car models realistically portray a...
108,S32_4289,1928 Ford Phaeton Deluxe,Vintage Cars,Our Vintage Car models realistically portray a...
109,S50_1341,1930 Buick Marquette Phaeton,Vintage Cars,Our Vintage Car models realistically portray a...

In [8]:
run("""
SELECT 
    orderNumber, 
    productName, 
    msrp, 
    priceEach
FROM
    products p
        INNER JOIN
    orderdetails o ON p.productcode = o.productcode
        AND p.msrp > o.priceEach
WHERE
    p.productcode = 'S10_1678'
""")

    orderNumber                            productName  msrp  priceEach
0         10107  1969 Harley Davidson Ultimate Chopper  95.7      81.35
1         10121  1969 Harley Davidson Ultimate Chopper  95.7      86.13
2         10134  1969 Harley Davidson Ultimate Chopper  95.7      90.92
3         10145  1969 Harley Davidson Ultimate Chopper  95.7      76.56
4         10159  1969 Harley Davidson Ultimate Chopper  95.7      81.35
5         10168  1969 Harley Davidson Ultimate Chopper  95.7      94.74
6         10180  1969 Harley Davidson Ultimate Chopper  95.7      76.56
7         10201  1969 Harley Davidson Ultimate Chopper  95.7      82.30
8         10211  1969 Harley Davidson Ultimate Chopper  95.7      90.92
9         10223  1969 Harley Davidson Ultimate Chopper  95.7      80.39
10        10237  1969 Harley Davidson Ultimate Chopper  95.7      91.87
11        10251  1969 Harley Davidson Ultimate Chopper  95.7      93.79
12        10263  1969 Harley Davidson Ultimate Chopper  95.7      89.00
13        10275  1969 Harley Davidson Ultimate Chopper  95.7      81.35
14        10299  1969 Harley Davidson Ultimate Chopper  95.7      76.56
15        10309  1969 Harley Davidson Ultimate Chopper  95.7      94.74
16        10318  1969 Harley Davidson Ultimate Chopper  95.7      84.22
17        10329  1969 Harley Davidson Ultimate Chopper  95.7      80.39
18        10341  1969 Harley Davidson Ultimate Chopper  95.7      84.22
19        10354  1969 Harley Davidson Ultimate Chopper  95.7      84.22
20        10361  1969 Harley Davidson Ultimate Chopper  95.7      92.83
21        10375  1969 Harley Davidson Ultimate Chopper  95.7      76.56
22        10388  1969 Harley Davidson Ultimate Chopper  95.7      80.39
23        10399  1969 Harley Davidson Ultimate Chopper  95.7      77.52
24        10403  1969 Harley Davidson Ultimate Chopper  95.7      85.17
25        10417  1969 Harley Davidson Ultimate Chopper  95.7      79.43

In [6]:
run("""
SELECT 
    productCode, 
    productName, 
    textDescription
FROM
    products
        INNER JOIN
    productlines USING (productline)
""")

,productCode,productName,textDescription
0,S10_1949,1952 Alpine Renault 1300,Attention car enthusiasts: Make your wildest c...
1,S10_4757,1972 Alfa Romeo GTA,Attention car enthusiasts: Make your wildest c...
2,S10_4962,1962 LanciaA Delta 16V,Attention car enthusiasts: Make your wildest c...
3,S12_1099,1968 Ford Mustang,Attention car enthusiasts: Make your wildest c...
4,S12_1108,2001 Ferrari Enzo,Attention car enthusiasts: Make your wildest c...
5,S12_3148,1969 Corvair Monza,Attention car enthusiasts: Make your wildest c...
6,S12_3380,1968 Dodge Charger,Attention car enthusiasts: Make your wildest c...
7,S12_3891,1969 Ford Falcon,Attention car enthusiasts: Make your wildest c...
8,S12_3990,1970 Plymouth Hemi Cuda,Attention car enthusiasts: Make your wildest c...
9,S12_4675,1969 Dodge Charger,Attention car enthusiasts: Make your wildest c...
10,S18_1129,1993 Mazda RX-7,Attention car enthusiasts: Make your wildest c...
11,S18_1589,1965 Aston Martin DB5,Attention car enthusiasts: Make your wildest c...
12,S18_1889,1948 Porsche 356-A Roadster,Attention car enthusiasts: Make your wildest c...
13,S18_1984,1995 Honda Civic,Attention car enthusiasts: Make your wildest c...
14,S18_2238,1998 Chrysler Plymouth Prowler,Attention car enthusiasts: Make your wildest c...
15,S18_2870,1999 Indy 500 Monte Carlo SS,Attention car enthusiasts: Make your wildest c...
16,S18_3232,1992 Ferrari 360 Spider red,Attention car enthusiasts: Make your wildest c...
17,S18_3233,1985 Toyota Supra,Attention car enthusiasts: Make your wildest c...
18,S18_3278,1969 Dodge Super Bee,Attention car enthusiasts: Make your wildest c...
19,S18_3482,1976 Ford Gran Torino,Attention car enthusiasts: Make your wildest c...
20,S18_3685,1948 Porsche Type 356 Roadster,Attention car enthusiasts: Make your wildest c...
21,S18_4027,1970 Triumph Spitfire,Attention car enthusiasts: Make your wildest c...
22,S18_4721,1957 Corvette Convertible,Attention car enthusiasts: Make your wildest c...
23,S18_4933,1957 Ford Thunderbird,Attention car enthusiasts: Make your wildest c...
24,S24_1046,1970 Chevy Chevelle SS 454,Attention car enthusiasts: Make your wildest c...
25,S24_1444,1970 Dodge Coronet,Attention car enthusiasts: Make your wildest c...
26,S24_1628,1966 Shelby Cobra 427 S/C,Attention car enthusiasts: Make your wildest c...
27,S24_2766,1949 Jaguar XK 120,Attention car enthusiasts: Make your wildest c...
28,S24_2840,1958 Chevy Corvette Limited Edition,Attention car enthusiasts: Make your wildest c...
29,S24_2887,1952 Citroen-15CV,Attention car enthusiasts: Make your wildest c...
...,...,...,...
80,S18_4600,1940s Ford truck,The Truck and Bus models are realistic replica...
81,S24_2300,1962 Volkswagen Microbus,The Truck and Bus models are realistic replica...
82,S32_1268,1980’s GM Manhattan Express,The Truck and Bus models are realistic replica...
83,S32_2509,1954 Greyhound Scenicruiser,The Truck and Bus models are realistic replica...
84,S32_3522,1996 Peterbilt 379 Stake Bed with Outrigger,The Truck and Bus models are realistic replica...
85,S50_1392,Diamond T620 Semi-Skirted Tanker,The Truck and Bus models are realistic replica...
86,S18_1342,1937 Lincoln Berline,Our Vintage Car models realistically portray a...
87,S18_1367,1936 Mercedes-Benz 500K Special Roadster,Our Vintage Car models realistically portray a...
88,S18_1749,1917 Grand Touring Sedan,Our Vintage Car models realistically portray a...
89,S18_2248,1911 Ford Town Car,Our Vintage Car models realistically portray a...
90,S18_2325,1932 Model A Ford J-Coupe,Our Vintage Car models realistically portray a...
91,S18_2795,1928 Mercedes-Benz SSK,Our Vintage Car models realistically portray a...
92,S18_2949,1913 Ford Model T Speedster,Our Vintage Car models realistically portray a...
93,S18_2957,1934 Ford V8 Coupe,Our Vintage Car models realistically portray a...
94,S18_3136,18th Century Vintage Horse Carriage,Our Vintage Car models realistically portray a...
95,S18_3140,1903 Ford Model A,Our Vintage Car models realistically portray a...
96,S18_3320,1917 Maxwell Touring Car,Our Vintage Car models realistically portray a...
97,S18_3856,1941 Chevrolet Special Deluxe Cabriolet,Our Vintage Car models realistically portray a...
98,S18_4409,1932 Alfa Romeo 8C2300 Spider Sport,Our Vintage Car models realistically portray a...
99,S18_4522,1904 Buick Runabout,Our Vintage Car models realistically portray a...
100,S18_4668,1939 Cadillac Limousine,Our Vintage Car models realistically portray a...
101,S24_1937,1939 Chevrolet Deluxe Coupe,Our Vintage Car models realistically portray a...
102,S24_2022,1938 Cadillac V-16 Presidential Limousine,Our Vintage Car models realistically portray a...
103,S24_3151,1912 Ford Model T Delivery Wagon,Our Vintage Car models realistically portray a...
104,S24_3420,1937 Horch 930V Limousine,Our Vintage Car models realistically portray a...
105,S24_3816,1940 Ford Delivery Sedan,Our Vintage Car models realistically portray a...
106,S24_3969,1936 Mercedes Benz 500k Roadster,Our Vintage Car models realistically portray a...
107,S24_4258,1936 Chrysler Airflow,Our Vintage Car models realistically portray a...
108,S32_4289,1928 Ford Phaeton Deluxe,Our Vintage Car models realistically portray a...
109,S50_1341,1930 Buick Marquette Phaeton,Our Vintage Car models realistically portray a...

In [9]:
#bisa mendeteksi customer yang tidak melakukan transaksi
#Left join untuk menampilkan seluruh data meskipun ada data yang tidak berisi
run("""
SELECT
 c.customerNumber,
 c.customerName,
 orderNumber,
 o.status
FROM
 customers c
LEFT JOIN orders o ON c.customerNumber = o.customerNumber
""")

     customerNumber                    customerName  orderNumber      status
0               103               Atelier graphique      10123.0     Shipped
1               103               Atelier graphique      10298.0     Shipped
2               103               Atelier graphique      10345.0     Shipped
3               112              Signal Gift Stores      10124.0     Shipped
4               112              Signal Gift Stores      10278.0     Shipped
5               112              Signal Gift Stores      10346.0     Shipped
6               114      Australian Collectors, Co.      10120.0     Shipped
7               114      Australian Collectors, Co.      10125.0     Shipped
8               114      Australian Collectors, Co.      10223.0     Shipped
9               114      Australian Collectors, Co.      10342.0     Shipped
10              114      Australian Collectors, Co.      10347.0     Shipped
11              119               La Rochelle Gifts      10275.0     Shipped
12              119               La Rochelle Gifts      10315.0     Shipped
13              119               La Rochelle Gifts      10375.0     Shipped
14              119               La Rochelle Gifts      10425.0  In Process
15              121              Baane Mini Imports      10103.0     Shipped
16              121              Baane Mini Imports      10158.0     Shipped
17              121              Baane Mini Imports      10309.0     Shipped
18              121              Baane Mini Imports      10325.0     Shipped
19              124    Mini Gifts Distributors Ltd.      10113.0     Shipped
20              124    Mini Gifts Distributors Ltd.      10135.0     Shipped
21              124    Mini Gifts Distributors Ltd.      10142.0     Shipped
22              124    Mini Gifts Distributors Ltd.      10182.0     Shipped
23              124    Mini Gifts Distributors Ltd.      10229.0     Shipped
24              124    Mini Gifts Distributors Ltd.      10271.0     Shipped
25              124    Mini Gifts Distributors Ltd.      10282.0     Shipped
26              124    Mini Gifts Distributors Ltd.      10312.0     Shipped
27              124    Mini Gifts Distributors Ltd.      10335.0     Shipped
28              124    Mini Gifts Distributors Ltd.      10357.0     Shipped
29              124    Mini Gifts Distributors Ltd.      10368.0     Shipped
..              ...                             ...          ...         ...
320             459                Warburg Exchange          NaN        None
321             462                FunGiftIdeas.com      10166.0     Shipped
322             462                FunGiftIdeas.com      10321.0     Shipped
323             462                FunGiftIdeas.com      10388.0     Shipped
324             465             Anton Designs, Ltd.          NaN        None
325             471    Australian Collectables, Ltd      10193.0     Shipped
326             471    Australian Collectables, Ltd      10265.0     Shipped
327             471    Australian Collectables, Ltd      10415.0    Disputed
328             473              Frau da Collezione      10157.0     Shipped
329             473              Frau da Collezione      10218.0     Shipped
330             475     West Coast Collectables Co.      10199.0     Shipped
331             475     West Coast Collectables Co.      10215.0     Shipped
332             477             Mit Vergnügen & Co.          NaN        None
333             480       Kremlin Collectables, Co.          NaN        None
334             481              Raanan Stores, Inc          NaN        None
335             484      Iberia Gift Imports, Corp.      10184.0     Shipped
336             484      Iberia Gift Imports, Corp.      10303.0     Shipped
337             486    Motor Mint Distributors Inc.      10109.0     Shipped
338             486    Motor Mint Distributors Inc.      10236.0     Shipped
339             486    Motor Mint Distributors Inc.      10331.0     Shipped
340             487        Signal Collectibles Ltd.      10149.0     Shipped
341             487        Signal Collectibles Ltd.      10219.0     Shipped
342             489  Double Decker Gift Stores, Ltd      10186.0     Shipped
343             489  Double Decker Gift Stores, Ltd      10213.0     Shipped
344             495            Diecast Collectables      10207.0     Shipped
345             495            Diecast Collectables      10243.0     Shipped
346             496               Kelly's Gift Shop      10138.0     Shipped
347             496               Kelly's Gift Shop      10179.0   Cancelled
348             496               Kelly's Gift Shop      10360.0     Shipped
349             496               Kelly's Gift Shop      10399.0     Shipped

[350 rows x 4 columns]

In [12]:
run("""
SELECT 
    o.orderNumber, 
    customerNumber, 
    productCode
FROM
    orders o
        LEFT JOIN
    orderDetails USING (orderNumber)
WHERE
    orderNumber = 10123
""")

   orderNumber  customerNumber productCode
0        10123             103    S18_1589
1        10123             103    S18_2870
2        10123             103    S18_3685
3        10123             103    S24_1628

In [11]:
run("""
SELECT 
    o.orderNumber, 
    customerNumber, 
    productCode
FROM
    orders o
        LEFT JOIN
    orderDetails d ON o.orderNumber = d.orderNumber
        AND o.orderNumber = 10123
""")

     orderNumber  customerNumber productCode
0          10123             103    S18_1589
1          10123             103    S18_2870
2          10123             103    S18_3685
3          10123             103    S24_1628
4          10298             103        None
5          10345             103        None
6          10124             112        None
7          10278             112        None
8          10346             112        None
9          10120             114        None
10         10125             114        None
11         10223             114        None
12         10342             114        None
13         10347             114        None
14         10275             119        None
15         10315             119        None
16         10375             119        None
17         10425             119        None
18         10103             121        None
19         10158             121        None
20         10309             121        None
21         10325             121        None
22         10113             124        None
23         10135             124        None
24         10142             124        None
25         10182             124        None
26         10229             124        None
27         10271             124        None
28         10282             124        None
29         10312             124        None
..           ...             ...         ...
299        10242             456        None
300        10319             456        None
301        10126             458        None
302        10214             458        None
303        10348             458        None
304        10166             462        None
305        10321             462        None
306        10388             462        None
307        10193             471        None
308        10265             471        None
309        10415             471        None
310        10157             473        None
311        10218             473        None
312        10199             475        None
313        10215             475        None
314        10184             484        None
315        10303             484        None
316        10109             486        None
317        10236             486        None
318        10331             486        None
319        10149             487        None
320        10219             487        None
321        10186             489        None
322        10213             489        None
323        10207             495        None
324        10243             495        None
325        10138             496        None
326        10179             496        None
327        10360             496        None
328        10399             496        None

[329 rows x 3 columns]

In [20]:
run("""
SELECT 
    concat(e.firstName,' ', e.lastName) salesman, 
    e.jobTitle, 
    customerName
FROM
    employees e
        RIGHT JOIN
    customers c ON e.employeeNumber = c.salesRepEmployeeNumber
        AND e.jobTitle = 'Sales Rep'
ORDER BY customerName
""")

             salesman   jobTitle                        customerName
0    Gerard Hernandez  Sales Rep                        Alpha Cognac
1      Foon Yue Tseng  Sales Rep              American Souvenirs Inc
2     Pamela Castillo  Sales Rep                  Amica Models & Co.
3                None       None                       ANG Resellers
4         Andy Fixter  Sales Rep             Anna's Decorations, Ltd
5                None       None                 Anton Designs, Ltd.
6                None       None          Asian Shopping Network, Co
7                None       None               Asian Treasures, Inc.
8    Gerard Hernandez  Sales Rep                   Atelier graphique
9         Andy Fixter  Sales Rep        Australian Collectables, Ltd
10        Andy Fixter  Sales Rep          Australian Collectors, Co.
11        Andy Fixter  Sales Rep         Australian Gift Network, Co
12   Gerard Hernandez  Sales Rep                Auto Associés & Cie.
13        Loui Bondur  Sales Rep                   Auto Canal+ Petit
14    Steve Patterson  Sales Rep             Auto-Moto Classics Inc.
15         Larry Bott  Sales Rep                      AV Stores, Co.
16        Barry Jones  Sales Rep                  Baane Mini Imports
17        Barry Jones  Sales Rep  Bavarian Collectables Imports, Co.
18               None       None                   BG&E Collectables
19        Barry Jones  Sales Rep                Blauer See Auto, Co.
20    Leslie Thompson  Sales Rep                   Boards & Toys Co.
21      Martin Gerard  Sales Rep                         CAF Imports
22     Julie Firrelli  Sales Rep          Cambridge Collectables Co.
23      George Vanauf  Sales Rep      Canadian Gift Exchange Network
24     Julie Firrelli  Sales Rep             Classic Gift Ideas, Inc
25     Foon Yue Tseng  Sales Rep                Classic Legends Inc.
26        Barry Jones  Sales Rep             Clover Collections, Co.
27    Leslie Thompson  Sales Rep        Collectable Mini Designs Co.
28     Julie Firrelli  Sales Rep          Collectables For Less Inc.
29    Leslie Jennings  Sales Rep            Corporate Gift Ideas Co.
..                ...        ...                                 ...
92               None       None                  Raanan Stores, Inc
93        Loui Bondur  Sales Rep                  Reims Collectables
94    Pamela Castillo  Sales Rep                       Rovelli Gifts
95      George Vanauf  Sales Rep   Royal Canadian Collectables, Ltd.
96    Pamela Castillo  Sales Rep                        Royale Belge
97    Pamela Castillo  Sales Rep               Salzburg Collectables
98               None       None                SAR Distributors, Co
99        Loui Bondur  Sales Rep              Saveley & Henriot, Co.
100       Barry Jones  Sales Rep             Scandinavian Gift Ideas
101              None       None                    Schuyler Imports
102   Leslie Jennings  Sales Rep            Signal Collectibles Ltd.
103   Leslie Thompson  Sales Rep                  Signal Gift Stores
104       Andy Fixter  Sales Rep           Souveniers And Things Co.
105              None       None      Stuttgart Collectable Exchange
106        Larry Bott  Sales Rep            Stylish Desk Decors, Co.
107        Larry Bott  Sales Rep                 Suominen Souveniers
108    Foon Yue Tseng  Sales Rep                    Super Scale Inc.
109   Leslie Jennings  Sales Rep                Technics Stores Inc.
110     George Vanauf  Sales Rep             Tekni Collectables Inc.
111   Leslie Jennings  Sales Rep           The Sharp Gifts Warehouse
112        Mami Nishi  Sales Rep             Tokyo Collectables, Ltd
113       Barry Jones  Sales Rep             Toms Spezialitäten, Ltd
114        Larry Bott  Sales Rep                Toys of Finland, Co.
115   Leslie Thompson  Sales Rep                   Toys4GrownUps.com
116        Larry Bott  Sales Rep               UK Collectables, Ltd.
117     Martin Gerard  Sales Rep                     Vida Sport, Ltd
118    Foon Yue Tseng  Sales Rep                     Vitachrome Inc.
119       Barry Jones  Sales Rep            Volvo Model Replicas, Co
120              None       None                    Warburg Exchange
121   Leslie Thompson  Sales Rep         West Coast Collectables Co.

[122 rows x 3 columns]

In [21]:
run("""
SELECT 
    CONCAT(m.lastname, ', ', m.firstname) AS 'Manager',
    CONCAT(e.lastname, ', ', e.firstname) AS 'Direct report'
FROM
    employees e
        INNER JOIN
    employees m ON m.employeeNumber = e.reportsto
ORDER BY manager
""")

               Manager       Direct report
0       Bondur, Gerard   Hernandez, Gerard
1       Bondur, Gerard        Bondur, Loui
2       Bondur, Gerard      Gerard, Martin
3       Bondur, Gerard        Jones, Barry
4       Bondur, Gerard         Bott, Larry
5       Bondur, Gerard    Castillo, Pamela
6         Bow, Anthony     Firrelli, Julie
7         Bow, Anthony    Thompson, Leslie
8         Bow, Anthony    Jennings, Leslie
9         Bow, Anthony      Vanauf, George
10        Bow, Anthony     Tseng, Foon Yue
11        Bow, Anthony    Patterson, Steve
12       Murphy, Diane      Firrelli, Jeff
13       Murphy, Diane     Patterson, Mary
14         Nishi, Mami       Kato, Yoshimi
15     Patterson, Mary  Patterson, William
16     Patterson, Mary        Bow, Anthony
17     Patterson, Mary      Bondur, Gerard
18     Patterson, Mary         Nishi, Mami
19  Patterson, William           King, Tom
20  Patterson, William        Marsh, Peter
21  Patterson, William        Fixter, Andy

In [22]:


run("""
SELECT 
    IFNULL(CONCAT(m.lastname, ', ', m.firstname),
            'Top Manager') AS 'Manager',
    CONCAT(e.lastname, ', ', e.firstname) AS 'Direct report'
FROM
    employees e
        LEFT JOIN
    employees m ON m.employeeNumber = e.reportsto
ORDER BY manager DESC
""")

               Manager       Direct report
0          Top Manager       Murphy, Diane
1   Patterson, William        Marsh, Peter
2   Patterson, William        Fixter, Andy
3   Patterson, William           King, Tom
4      Patterson, Mary        Bow, Anthony
5      Patterson, Mary      Bondur, Gerard
6      Patterson, Mary         Nishi, Mami
7      Patterson, Mary  Patterson, William
8          Nishi, Mami       Kato, Yoshimi
9        Murphy, Diane      Firrelli, Jeff
10       Murphy, Diane     Patterson, Mary
11        Bow, Anthony    Thompson, Leslie
12        Bow, Anthony    Jennings, Leslie
13        Bow, Anthony      Vanauf, George
14        Bow, Anthony     Tseng, Foon Yue
15        Bow, Anthony    Patterson, Steve
16        Bow, Anthony     Firrelli, Julie
17      Bondur, Gerard        Bondur, Loui
18      Bondur, Gerard      Gerard, Martin
19      Bondur, Gerard        Jones, Barry
20      Bondur, Gerard         Bott, Larry
21      Bondur, Gerard    Castillo, Pamela
22      Bondur, Gerard   Hernandez, Gerard

In [23]:
run("""
SELECT 
    c1.city, c1.customerName, c2.customerName
FROM
    customers c1
        INNER JOIN
    customers c2 ON c1.city = c2.city
        AND c1.customername > c2.customerName
ORDER BY c1.city
""")

,city,customerName,customerName
0,Auckland,Kelly's Gift Shop,GiftsForHim.com
1,Auckland,Kelly's Gift Shop,"Down Under Souveniers, Inc"
2,Auckland,GiftsForHim.com,"Down Under Souveniers, Inc"
3,Boston,Gifts4AllAges.com,Diecast Collectables
4,Brickhaven,Collectables For Less Inc.,Auto-Moto Classics Inc.
5,Brickhaven,Online Mini Collectables,Collectables For Less Inc.
6,Brickhaven,Online Mini Collectables,Auto-Moto Classics Inc.
7,Cambridge,Marta's Replicas Co.,Cambridge Collectables Co.
8,Frankfurt,Messner Shopping Network,"Blauer See Auto, Co."
9,Glendale,Gift Ideas Corp.,Boards & Toys Co.
10,Lisboa,Porto Imports Co.,"Lisboa Souveniers, Inc"
11,London,"Stylish Desk Decors, Co.","Double Decker Gift Stores, Ltd"
12,Madrid,"Corrida Auto Replicas, Ltd",ANG Resellers
13,Madrid,Euro+ Shopping Channel,"Anton Designs, Ltd."
14,Madrid,CAF Imports,ANG Resellers
15,Madrid,"Corrida Auto Replicas, Ltd",CAF Imports
16,Madrid,"Corrida Auto Replicas, Ltd","Anton Designs, Ltd."
17,Madrid,"Anton Designs, Ltd.",ANG Resellers
18,Madrid,Euro+ Shopping Channel,ANG Resellers
19,Madrid,Euro+ Shopping Channel,CAF Imports
20,Madrid,CAF Imports,"Anton Designs, Ltd."
21,Madrid,Euro+ Shopping Channel,"Corrida Auto Replicas, Ltd"
22,Nantes,La Rochelle Gifts,Atelier graphique
23,New Bedford,Mini Creations Ltd.,FunGiftIdeas.com
24,New Haven,Super Scale Inc.,American Souvenirs Inc
25,NYC,Microscale Inc.,Classic Legends Inc.
26,NYC,Vitachrome Inc.,Muscle Machine Inc
27,NYC,Land of Toys Inc.,Classic Legends Inc.
28,NYC,Vitachrome Inc.,Land of Toys Inc.
29,NYC,Vitachrome Inc.,Microscale Inc.
30,NYC,Vitachrome Inc.,Classic Legends Inc.
31,NYC,Muscle Machine Inc,Land of Toys Inc.
32,NYC,Muscle Machine Inc,Microscale Inc.
33,NYC,Muscle Machine Inc,Classic Legends Inc.
34,NYC,Microscale Inc.,Land of Toys Inc.
35,Paris,Lyon Souveniers,"La Corne D'abondance, Co."
36,Paris,Lyon Souveniers,Auto Canal+ Petit
37,Paris,"La Corne D'abondance, Co.",Auto Canal+ Petit
38,Philadelphia,Motor Mint Distributors Inc.,"Classic Gift Ideas, Inc"
39,San Francisco,Mini Wheels Co.,Corporate Gift Ideas Co.
40,Singapore,Handji Gifts& Co,"Dragon Souveniers, Ltd."
41,Singapore,Handji Gifts& Co,"Asian Shopping Network, Co"
42,Singapore,"Dragon Souveniers, Ltd.","Asian Shopping Network, Co"

In [29]:
run("""
SELECT 
    customerName, amount, paymentDate
FROM
    payments t1
        INNER JOIN
    customers t2 ON t1.customerNumber = t2.customerNumber
    ORDER BY amount
""")

                     customerName     amount paymentDate
0         Tokyo Collectables, Ltd     615.45  2005-05-18
1                    Royale Belge    1128.20  2003-08-22
2              Baane Mini Imports    1491.38  2003-10-28
3                    Royale Belge    1627.56  2003-04-19
4               Atelier graphique    1676.14  2004-12-18
5                 Microscale Inc.    1679.92  2004-04-30
6            Marseille Mini Autos    1834.56  2005-01-29
7       La Corne D'abondance, Co.    1960.80  2004-09-09
8            Technics Stores Inc.    2434.25  2004-11-14
9         Dragon Souveniers, Ltd.    2611.84  2004-08-11
10     Down Under Souveniers, Inc    2880.00  2003-07-05
11             Enaco Distributors    3101.40  2003-05-09
12              Boards & Toys Co.    3452.75  2005-03-02
13     Iberia Gift Imports, Corp.    3474.66  2004-10-26
14        Dragon Souveniers, Ltd.    3516.04  2005-03-27
15              Toys4GrownUps.com    3879.96  2003-12-04
16       Online Mini Collectables    4424.40  2004-09-24
17              Boards & Toys Co.    4465.85  2003-10-18
18                    Mini Caravy    4632.31  2004-06-21
19       Danish Wholesale Imports    4710.73  2004-07-03
20                Vitachrome Inc.    5494.78  2003-01-30
21           Auto Associés & Cie.    5759.42  2004-02-10
22        Auto-Moto Classics Inc.    5858.56  2004-09-21
23   Motor Mint Distributors Inc.    5899.38  2004-04-14
24        Auto-Moto Classics Inc.    6036.96  2003-07-06
25              Atelier graphique    6066.78  2004-10-19
26           Diecast Collectables    6276.60  2004-05-14
27          Salzburg Collectables    6419.84  2004-08-01
28               Gift Ideas Corp.    6631.36  2003-09-15
29        Tekni Collectables Inc.    7178.66  2004-04-16
..                            ...        ...         ...
243           Mini Creations Ltd.   52548.49  2003-11-24
244                AV Stores, Co.   52825.29  2004-11-03
245          Auto Associés & Cie.   53116.99  2004-10-22
246          Heintze Collectables   53745.34  2004-11-02
247      Danish Wholesale Imports   53959.21  2003-02-20
248  Online Diecast Creations Co.   55425.77  2003-12-05
249  Mini Gifts Distributors Ltd.   55639.66  2004-11-02
250    Corrida Auto Replicas, Ltd   57131.92  2003-06-13
251            Muscle Machine Inc   58793.53  2003-12-22
252            Muscle Machine Inc   58841.35  2003-06-18
253          Diecast Collectables   59265.14  2003-12-26
254     The Sharp Gifts Warehouse   59551.38  2004-06-21
255        Euro+ Shopping Channel   59830.55  2004-01-30
256       Toms Spezialitäten, Ltd   61234.67  2004-11-06
257               Vida Sport, Ltd   61402.00  2004-09-18
258         Diecast Classics Inc.   63357.13  2004-09-07
259        Euro+ Shopping Channel   63843.55  2003-12-09
260        Euro+ Shopping Channel   65071.26  2005-03-25
261    Down Under Souveniers, Inc   75020.13  2005-05-23
262  Collectable Mini Designs Co.   80375.24  2004-03-15
263    Australian Collectors, Co.   82261.22  2004-12-15
264  Mini Gifts Distributors Ltd.   83598.04  2005-04-16
265                  Herkku Gifts   85024.46  2003-12-03
266  Mini Gifts Distributors Ltd.   85410.87  2004-08-28
267      Corporate Gift Ideas Co.   85559.12  2003-11-03
268  Mini Gifts Distributors Ltd.  101244.59  2005-03-05
269       Dragon Souveniers, Ltd.  105743.00  2003-12-26
270  Mini Gifts Distributors Ltd.  111654.40  2003-08-15
271        Euro+ Shopping Channel  116208.40  2004-12-31
272        Euro+ Shopping Channel  120166.58  2005-03-18

[273 rows x 3 columns]